apiVersion: skaffold/v2alpha3
kind: Config
deploy:
  kubectl:
    manifests:
      - ./infra/k8s/*
build:
  local:
    push: false
  artifacts:
    - image: moonsh4ke/kllejero-auth
      context: auth_service
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: 'src/**/*.ts'
            dest: .
    - image: moonsh4ke/kllejero-test-nats
      context: test_nats
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: 'src/**/*.ts'
            dest: .
    - image: moonsh4ke/kllejero-populator
      context: populator_service
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: 'src/**/*.py'
            dest: .
