gen_file_id = {
    "Host": "www.mercadopublico.cl",
    "User-Agent": "Mozilla/5.0 (X11; Linux x86_64; rv:124.0) Gecko/20100101 Firefox/124.0",
    "Accept": "application/json, text/javascript, */*; q=0.01",
    "Accept-Language": "en-US,en;q=0.5",
    "Accept-Encoding": "gzip, deflate, br",
    "Content-Type": "application/json; charset=utf-8",
    "X-Requested-With": "XMLHttpRequest",
    "Content-Length": "343",
    "Origin": "https://www.mercadopublico.cl",
    "Connection": "keep-alive",
    "Referer": "https://www.mercadopublico.cl/BuscarLicitacion?IsFirstTableDesign=True",
    "Cookie": "__RequestVerificationToken_L0hvbWU1=7BlfduMW191MDC2e8bMQCcf9gAnqokLG0TFcvssnWaM489VYkErhvVjdKCREvDTwZsxiF4FgpkY0Suk0tSO98FF1mHVPznu28CsqiCjQwPB1gSa9wA50gtJqOrY1; ASP.NET_SessionId=fa3stnxmuqijtqhnsjhhbyrd",
    "Sec-Fetch-Dest": "empty",
    "Sec-Fetch-Mode": "cors",
    "Sec-Fetch-Site": "same-origin",
    "DNT": "1",
    "Sec-GPC": "1",
}


download_tenders_file = {
    "Host": "www.mercadopublico.cl",
    "User-Agent": "Mozilla/5.0 (X11; Linux x86_64; rv:124.0) Gecko/20100101 Firefox/124.0",
    "Accept": "text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,*/*;q=0.8",
    "Accept-Language": "en-US,en;q=0.5",
    "Accept-Encoding": "gzip, deflate, br",
    "Connection": "keep-alive",
    "Referer": "https://www.mercadopublico.cl/BuscarLicitacion?IsFirstTableDesign=True",
    "Cookie": "__RequestVerificationToken_L0hvbWU1=7BlfduMW191MDC2e8bMQCcf9gAnqokLG0TFcvssnWaM489VYkErhvVjdKCREvDTwZsxiF4FgpkY0Suk0tSO98FF1mHVPznu28CsqiCjQwPB1gSa9wA50gtJqOrY1; ASP.NET_SessionId=fa3stnxmuqijtqhnsjhhbyrd",
    "Upgrade-Insecure-Requests": "1",
    "Sec-Fetch-Dest": "iframe",
    "Sec-Fetch-Mode": "navigate",
    "Sec-Fetch-Site": "same-origin",
    "Sec-Fetch-User": "?1",
    "DNT": "1",
    "Sec-GPC": "1",
}
