apiVersion: apps/v1
kind: Deployment
metadata:
  name: notification-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: notification
  template:
    metadata:
      labels:
        app: notification
    spec:
      containers:
        - name: notification
          image: hoffens/kllejero-notification
          ports:
            - containerPort: 7070
          env:
            - name: ASPNETCORE_URLS
              value: "http://*:7070"
            - name: DB_CONNECTION_STRING
              value: "server=kllejero.cwy4hbuwhvsr.us-east-1.rds.amazonaws.com;port=3306;database=notification-db;user=admin;password=MU53F3fUAq"
            - name: NATS_URL
              value: "nats://nats:4222"
            - name: JWT_KEY
              valueFrom:
                secretKeyRef:
                  name: jwt-secret
                  key: JWT_KEY
---
apiVersion: v1
kind: Service
metadata:
  name: notification-srv
spec:
  selector:
    app: notification
  ports:
    - name: notification
      protocol: TCP
      port: 7070
      targetPort: 7070
